# Default values for ray-cluster.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: path-to-your-image-repository
  tag: your-image-tag
  pullPolicy: IfNotPresent

nameOverride: "ray"
fullnameOverride: ""

imagePullSecrets: []
  # - name: an-existing-secret

head:
  groupName: headgroup
  replicas: 1
  type: head
  labels:
    key: value
  initArgs:
    port: '6379'
    redis-password: 'LetMeInRay'
    dashboard-host: '0.0.0.0'
    num-cpus: '1' # can be auto-completed from the limits
    node-ip-address: $MY_POD_IP # auto-completed as the head pod IP
    block: 'true'
  containerEnv:
    - name: MY_POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
  envFrom: []
    # - secretRef:
    #     name: my-env-secret
  resources:
    limits:
      cpu: 1
      #nvidia.com/gpu: 1
    requests:
       cpu: 1
       memory: '4G'
       #nvidia.com/gpu: 1
  annotations: { sidecar.istio.io/inject: "false" }
  nodeSelector: {}
  tolerations: []
  affinity: {}
  volumes:
    - name: log-volume
      emptyDir: { }
  volumeMounts:
    - mountPath: /tmp/ray
      name: log-volume


worker:
  groupName: workergroup
  replicas: 3 
  minReplicas: 3
  maxReplicas: 7
  type: worker
  labels:
    key: value
  initArgs:
    node-ip-address: $MY_POD_IP
    redis-password: LetMeInRay
    block: 'true'
  containerEnv:
    - name: MY_POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
    - name: RAY_DISABLE_DOCKER_CPU_WARNING
      value: "1"
    - name: CPU_REQUEST
      valueFrom:
        resourceFieldRef:
          containerName: ray-worker
          resource: requests.cpu
    - name: MY_POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
  envFrom: []
    # - secretRef:
    #     name: my-env-secret
  ports:
    - containerPort: 80
      protocol: TCP
  resources: 
    limits:
      cpu: 1
      #nvidia.com/gpu: 1
    requests:
       cpu: 1
       memory: '4G'
       #nvidia.com/gpu: 1
  annotations:
    sidecar.istio.io/inject: "false"
  nodeSelector: {}
  tolerations: []
  affinity: {}
  volumes:
    - name: log-volume
      emptyDir: {}
  volumeMounts:
    - mountPath: /tmp/ray
      name: log-volume

headServiceSuffix: "ray-operator.svc"

service:
  type: ClusterIP
  port: 8080
